package sshconfig

import (
	"fmt"
	"io"
)

// Write serializes host entries as an OpenSSH config fragment.
func Write(w io.Writer, entries []HostEntry) error {
	if _, err := io.WriteString(w, "# Generated by vexo — passwords, vault keys, icons, and dial proxies are not exported\n"); err != nil {
		return err
	}
	for i, e := range entries {
		if i > 0 {
			if _, err := io.WriteString(w, "\n"); err != nil {
				return err
			}
		}
		alias := e.Alias
		if alias == "" {
			alias = e.HostName
		}
		if alias == "" {
			continue
		}
		if _, err := fmt.Fprintf(w, "Host %s\n", quoteSSH(alias)); err != nil {
			return err
		}
		hostName := e.HostName
		if hostName == "" {
			hostName = alias
		}
		if err := writeKV(w, "HostName", hostName); err != nil {
			return err
		}
		if e.User != "" {
			if err := writeKV(w, "User", e.User); err != nil {
				return err
			}
		}
		if e.Port > 0 && e.Port != 22 {
			if err := writeKV(w, "Port", fmt.Sprintf("%d", e.Port)); err != nil {
				return err
			}
		}
		for _, id := range e.IdentityFiles {
			if id == "" {
				continue
			}
			if err := writeKV(w, "IdentityFile", id); err != nil {
				return err
			}
		}
		if e.CertificateFile != "" {
			if err := writeKV(w, "CertificateFile", e.CertificateFile); err != nil {
				return err
			}
		}
		if e.ProxyJump != "" {
			if err := writeKV(w, "ProxyJump", e.ProxyJump); err != nil {
				return err
			}
		}
		if e.ForwardAgent != nil && *e.ForwardAgent {
			if err := writeKV(w, "ForwardAgent", "yes"); err != nil {
				return err
			}
		}
		if e.RemoteCommand != "" {
			if err := writeKV(w, "RemoteCommand", e.RemoteCommand); err != nil {
				return err
			}
		}
		for _, kv := range e.SetEnv {
			if kv.Key == "" {
				continue
			}
			// Quote the value only — quoting "KEY=val" as a whole breaks parsers.
			if _, err := fmt.Fprintf(w, "  SetEnv %s=%s\n", kv.Key, quoteSSH(kv.Value)); err != nil {
				return err
			}
		}
	}
	return nil
}

func writeKV(w io.Writer, key, value string) error {
	_, err := fmt.Fprintf(w, "  %s %s\n", key, quoteSSH(value))
	return err
}
