// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A Logger provides fast, leveled, structured logging. All methods are safe
 * for concurrent use.
 * 
 * The Logger is designed for contexts in which every microsecond and every
 * allocation matters, so its API intentionally favors performance and type
 * safety over brevity. For most applications, the SugaredLogger strikes a
 * better balance between performance and ergonomics.
 */
export class Logger {

    /** Creates a new Logger instance. */
    constructor($$source: Partial<Logger> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Logger instance from a string or object.
     */
    static createFrom($$source: any = {}): Logger {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Logger($$parsedSource as Partial<Logger>);
    }
}
