//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../../../../ilaziness/vexo/services/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "sftpClose": $$createType0,
        "sshClose": $$createType0,
        "sshInput": $$createType0,
        "sshOutput": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = services$0.SSHEventData.createFrom;

configure();
