// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BookmarkService 书签服务结构
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddBookmark 新增SSH连接信息书签
 */
export function AddBookmark(bookmark: $models.SSHBookmark): $CancellablePromise<void> {
    return $Call.ByID(3315687774, bookmark);
}

/**
 * AddGroup 新增分组
 */
export function AddGroup(groupName: string): $CancellablePromise<void> {
    return $Call.ByID(2918050329, groupName);
}

/**
 * CloseWindow 关闭窗口
 */
export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(1703303817);
}

/**
 * DeleteBookmark 删除书签
 */
export function DeleteBookmark(bookmarkID: string): $CancellablePromise<void> {
    return $Call.ByID(1395345088, bookmarkID);
}

/**
 * DeleteGroup 删除分组
 */
export function DeleteGroup(groupName: string): $CancellablePromise<void> {
    return $Call.ByID(3070903619, groupName);
}

/**
 * GetBookmarkByID 通过书签ID查找返回连接信息
 */
export function GetBookmarkByID(bookmarkID: string): $CancellablePromise<$models.SSHBookmark | null> {
    return $Call.ByID(1843677837, bookmarkID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListBookmarks 列出所有书签
 */
export function ListBookmarks(): $CancellablePromise<($models.BookmarkGroup | null)[]> {
    return $Call.ByID(3708930492).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ShowWindow show bookmark manage window
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(2486392426);
}

/**
 * UpdateBookmark 更新SSH连接信息书签
 */
export function UpdateBookmark(bookmark: $models.SSHBookmark): $CancellablePromise<void> {
    return $Call.ByID(2848754130, bookmark);
}

/**
 * UpdateGroupName 更新分组名称
 */
export function UpdateGroupName(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(880299830, oldName, newName);
}

// Private type creation functions
const $$createType0 = $models.SSHBookmark.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.BookmarkGroup.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
