// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function MainWindowClose(): $CancellablePromise<void> {
    return $Call.ByID(3371547165);
}

export function MainWindowMax(): $CancellablePromise<void> {
    return $Call.ByID(2541474671);
}

export function MainWindowMin(): $CancellablePromise<void> {
    return $Call.ByID(2775081409);
}

export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(556670317);
}

export function SelectFile(): $CancellablePromise<string> {
    return $Call.ByID(3784135936);
}
