// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(1618294891);
}

/**
 * ReadConfig 读取配置方法，返回当前配置
 */
export function ReadConfig(): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(1067814135).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConfig 保存配置方法
 * 1. 如果 UserDataDir 改变，更新应用配置文件
 * 2. 将所有配置保存到用户配置文件
 */
export function SaveConfig(config: $models.Config): $CancellablePromise<void> {
    return $Call.ByID(3626712470, config);
}

export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(1623093136);
}

// Private type creation functions
const $$createType0 = $models.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
