// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} msg
 * @returns {$CancellablePromise<void>}
 */
export function Debug(msg) {
    return $Call.ByID(522036388, msg);
}

/**
 * @param {string} msg
 * @returns {$CancellablePromise<void>}
 */
export function Error(msg) {
    return $Call.ByID(3552014541, msg);
}

/**
 * @param {string} msg
 * @returns {$CancellablePromise<void>}
 */
export function Info(msg) {
    return $Call.ByID(1350211761, msg);
}

/**
 * @param {string} msg
 * @returns {$CancellablePromise<void>}
 */
export function Warn(msg) {
    return $Call.ByID(1624156293, msg);
}
