// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Debug(msg: string): $CancellablePromise<void> {
    return $Call.ByID(522036388, msg);
}

export function Error(msg: string): $CancellablePromise<void> {
    return $Call.ByID(3552014541, msg);
}

export function Info(msg: string): $CancellablePromise<void> {
    return $Call.ByID(1350211761, msg);
}

export function Warn(msg: string): $CancellablePromise<void> {
    return $Call.ByID(1624156293, msg);
}
