// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as os$0 from "../../../../os/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * FileInfo represents file information for SFTP operations
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {os$0.FileMode}
             */
            this["mode"] = $0.FileMode.$zero;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modTime"] = null;
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

export class SSHEventData {
    /**
     * Creates a new SSHEventData instance.
     * @param {Partial<SSHEventData>} [$$source = {}] - The source object to create the SSHEventData.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHEventData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHEventData}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new SSHEventData(/** @type {Partial<SSHEventData>} */($$parsedSource));
    }
}
