// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../../../../golang.org/x/crypto/ssh/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close closes the SFTP connection
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1661848074);
}

/**
 * Connect connects to SFTP using an SSH session ID
 */
export function Connect(sshClient: ssh$0.Client | null): $CancellablePromise<void> {
    return $Call.ByID(98731180, sshClient);
}

/**
 * CreateDirectory creates a new directory at the specified path
 */
export function CreateDirectory(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(3355703897, sessionID, path);
}

/**
 * CreateFile creates a new file at the specified path
 */
export function CreateFile(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1286489372, sessionID, path);
}

/**
 * DeleteFile deletes a file or directory at the specified path
 */
export function DeleteFile(sessionID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(1060872751, sessionID, path);
}

/**
 * DownloadDirectory recursively downloads a remote directory to the specified local path
 * if localPath empty string, it will open a file dialog to select a directory
 */
export function DownloadDirectory(sessionID: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1324595725, sessionID, localPath, remotePath);
}

/**
 * DownloadFile downloads a remote file to the specified local path
 */
export function DownloadFile(sessionID: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(3674394144, sessionID, localPath, remotePath);
}

/**
 * DownloadFileDialog opens a save dialog to select where to download a remote file
 */
export function DownloadFileDialog(sessionID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1153655184, sessionID, remotePath);
}

/**
 * GetFileInfo returns information about a file or directory
 */
export function GetFileInfo(sessionID: string, path: string): $CancellablePromise<$models.FileInfo> {
    return $Call.ByID(670845552, sessionID, path).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetWd returns the current working directory
 */
export function GetWd(sessionID: string): $CancellablePromise<string> {
    return $Call.ByID(3663044153, sessionID);
}

/**
 * ListFiles lists files and directories in the specified path
 */
export function ListFiles(sessionID: string, path: string, showHidden: boolean): $CancellablePromise<$models.FileInfo[]> {
    return $Call.ByID(1702531245, sessionID, path, showHidden).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * RenameFile renames a file or directory at the specified path
 */
export function RenameFile(sessionID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(3410560814, sessionID, oldPath, newPath);
}

/**
 * UploadDirectory recursively uploads a local directory to the specified remote path
 * if localPath empty string, it will open a file dialog to select a directory
 */
export function UploadDirectory(sessionID: string, localPath: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(1734072466, sessionID, localPath, remotePath);
}

/**
 * UploadFile uploads a local file to the specified remote path.
 * localPathFile is local file path with file full name.
 * remoteDir is remote directory without file name.
 */
export function UploadFile(sessionID: string, localPathFile: string, remoteDir: string): $CancellablePromise<void> {
    return $Call.ByID(3382460493, sessionID, localPathFile, remoteDir);
}

/**
 * UploadFileDialog opens a file dialog to select a file to upload
 */
export function UploadFileDialog(sessionID: string, remotePath: string): $CancellablePromise<void> {
    return $Call.ByID(2031720209, sessionID, remotePath);
}

// Private type creation functions
const $$createType0 = $models.FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
