// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close closes the SFTP connection
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(1661848074);
}

/**
 * Connect connects to SFTP using an SSH session ID
 * @param {string} sshSessionID
 * @returns {$CancellablePromise<void>}
 */
export function Connect(sshSessionID) {
    return $Call.ByID(98731180, sshSessionID);
}

/**
 * DeleteFile deletes a file or directory at the specified path
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(path) {
    return $Call.ByID(1060872751, path);
}

/**
 * DownloadFile downloads a remote file to the specified local path
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<void>}
 */
export function DownloadFile(remotePath, localPath) {
    return $Call.ByID(3674394144, remotePath, localPath);
}

/**
 * GetFileInfo returns information about a file or directory
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo>}
 */
export function GetFileInfo(path) {
    return $Call.ByID(670845552, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListFiles lists files and directories in the specified path
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListFiles(path) {
    return $Call.ByID(1702531245, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RenameFile renames a file or directory at the specified path
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameFile(oldPath, newPath) {
    return $Call.ByID(3410560814, oldPath, newPath);
}

/**
 * UploadFile uploads a local file to the specified remote path
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function UploadFile(localPath, remotePath) {
    return $Call.ByID(3382460493, localPath, remotePath);
}

// Private type creation functions
const $$createType0 = $models.FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
