// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Close closes all SSH connections managed by the service.
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3499207119);
}

/**
 * CloseByID closes the SSH connection with the specified ID.
 */
export function CloseByID(ID: string): $CancellablePromise<void> {
    return $Call.ByID(1418677895, ID);
}

/**
 * Connect establishes an SSH connection to the specified host using the provided credentials.
 * return session ID if success
 */
export function Connect(host: string, port: number, user: string, password: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(2551182453, host, port, user, password, key);
}

/**
 * Resize resizes the terminal for the SSH connection with the given ID.
 */
export function Resize(ID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(4201974589, ID, cols, rows);
}

/**
 * Restart restarts the SSH connection with the given ID.
 */
export function Restart(ID: string): $CancellablePromise<void> {
    return $Call.ByID(161586184, ID);
}

/**
 * SelectKeyFile 选择私钥文件
 */
export function SelectKeyFile(): $CancellablePromise<string> {
    return $Call.ByID(3142471558);
}

/**
 * Start starts the SSH connection with the given ID.
 */
export function Start(ID: string): $CancellablePromise<void> {
    return $Call.ByID(3362565939, ID);
}

/**
 * StartSftp create sftp service for the SSH connection
 */
export function StartSftp(ID: string): $CancellablePromise<void> {
    return $Call.ByID(2437975014, ID);
}
