// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Close closes all SSH connections managed by the service.
 * @returns {$CancellablePromise<void>}
 */
export function Close() {
    return $Call.ByID(3499207119);
}

/**
 * CloseByID closes the SSH connection with the specified ID.
 * @param {string} ID
 * @returns {$CancellablePromise<void>}
 */
export function CloseByID(ID) {
    return $Call.ByID(1418677895, ID);
}

/**
 * Connect establishes an SSH connection to the specified host using the provided credentials.
 * 连接成功返回数据ID
 * @param {string} host
 * @param {number} port
 * @param {string} user
 * @param {string} password
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function Connect(host, port, user, password, key) {
    return $Call.ByID(2551182453, host, port, user, password, key);
}

/**
 * Resize resizes the terminal for the SSH connection with the given ID.
 * @param {string} ID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(ID, cols, rows) {
    return $Call.ByID(4201974589, ID, cols, rows);
}

/**
 * SelectKeyFile 选择私钥文件
 * @returns {$CancellablePromise<string>}
 */
export function SelectKeyFile() {
    return $Call.ByID(3142471558);
}

/**
 * Start starts the SSH connection with the given ID.
 * @param {string} ID
 * @returns {$CancellablePromise<void>}
 */
export function Start(ID) {
    return $Call.ByID(3362565939, ID);
}
