// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * A FileMode represents a file's mode and permission bits.
 * The bits have the same definition on all systems, so that
 * information about files can be moved from one system
 * to another portably. Not all bits apply to all systems.
 * The only required bit is [ModeDir] for directories.
 * @typedef {$models.FileMode} FileMode
 */
