// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A FileMode represents a file's mode and permission bits.
 * The bits have the same definition on all systems, so that
 * information about files can be moved from one system
 * to another portably. Not all bits apply to all systems.
 * The only required bit is [ModeDir] for directories.
 * @readonly
 * @enum {number}
 */
export const FileMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * The defined file mode bits are the most significant bits of the [FileMode].
     * The nine least-significant bits are the standard Unix rwxrwxrwx permissions.
     * The values of these bits should be considered part of the public API and
     * may be used in wire protocols or disk representations: they must not be
     * changed, although new bits might be added.
     *
     * The single letters are the abbreviations
     * used by the String method's formatting.
     * d: is a directory
     */
    ModeDir: 2147483648,

    /**
     * a: append-only
     */
    ModeAppend: 1073741824,

    /**
     * l: exclusive use
     */
    ModeExclusive: 536870912,

    /**
     * T: temporary file; Plan 9 only
     */
    ModeTemporary: 268435456,

    /**
     * L: symbolic link
     */
    ModeSymlink: 134217728,

    /**
     * D: device file
     */
    ModeDevice: 67108864,

    /**
     * p: named pipe (FIFO)
     */
    ModeNamedPipe: 33554432,

    /**
     * S: Unix domain socket
     */
    ModeSocket: 16777216,

    /**
     * u: setuid
     */
    ModeSetuid: 8388608,

    /**
     * g: setgid
     */
    ModeSetgid: 4194304,

    /**
     * c: Unix character device, when ModeDevice is set
     */
    ModeCharDevice: 2097152,

    /**
     * t: sticky
     */
    ModeSticky: 1048576,

    /**
     * ?: non-regular file; nothing else is known about this file
     */
    ModeIrregular: 524288,

    /**
     * Mask for the type bits. For regular files, none will be set.
     */
    ModeType: 2401763328,

    /**
     * Unix permission bits
     */
    ModePerm: 511,
};
