import { TerminalThemes } from "../types/ssh";
import { darkTokens, eyeCareTokens, lightTokens } from "./paletteTokens";

/**
 * SSH GUI 客户端终端主题配置
 *
 * 锚点色来自 paletteTokens，与 MUI 主题保持同步。
 */
const terminalThemes: TerminalThemes = {
  light: {
    background: lightTokens.bgDefault,
    foreground: lightTokens.textPrimary,
    cursor: lightTokens.primary,
    cursorAccent: lightTokens.bgDefault,
    selectionBackground: lightTokens.primary,
    selectionForeground: "#FFFFFF",
    black: lightTokens.textPrimary,
    red: "#EF4444",
    green: lightTokens.success,
    yellow: "#F59E0B",
    blue: lightTokens.primary,
    magenta: "#8B5CF6",
    cyan: lightTokens.terminalCyan,
    white: lightTokens.textSecondary,
    brightBlack: "#94A3B8",
    brightRed: "#F87171",
    brightGreen: "#34D399",
    brightYellow: "#FBBF24",
    brightBlue: lightTokens.primaryLight,
    brightMagenta: "#A78BFA",
    brightCyan: "#22D3EE",
    brightWhite: "#E2E8F0",
  },
  dark: {
    background: darkTokens.bgDefault,
    foreground: darkTokens.textPrimary,
    cursor: darkTokens.secondary,
    cursorAccent: darkTokens.bgDefault,
    selectionBackground: darkTokens.primary,
    selectionForeground: darkTokens.bgDefault,
    black: darkTokens.bgDefault,
    red: "#F85149",
    green: darkTokens.ansiGreen,
    yellow: "#D29922",
    blue: darkTokens.primary,
    magenta: "#BC8CFF",
    cyan: darkTokens.terminalCyan,
    white: darkTokens.textPrimary,
    brightBlack: "#6E7681",
    brightRed: "#FF7B72",
    brightGreen: darkTokens.ansiBrightGreen,
    brightYellow: "#E3B341",
    brightBlue: darkTokens.primaryLight,
    brightMagenta: "#D2A8FF",
    brightCyan: "#39D353",
    brightWhite: "#F0F6FC",
  },
  eyeCare: {
    background: eyeCareTokens.bgDefault,
    foreground: eyeCareTokens.textPrimary,
    cursor: eyeCareTokens.primary,
    cursorAccent: eyeCareTokens.bgDefault,
    selectionBackground: eyeCareTokens.primary,
    selectionForeground: eyeCareTokens.bgDefault,
    black: eyeCareTokens.textPrimary,
    red: "#C2410C",
    green: eyeCareTokens.success,
    yellow: "#D97706",
    blue: eyeCareTokens.primaryDark,
    magenta: "#7C2D12",
    cyan: eyeCareTokens.terminalCyan,
    white: eyeCareTokens.textSecondary,
    brightBlack: "#A16207",
    brightRed: "#EA580C",
    brightGreen: "#84CC16",
    brightYellow: "#FBBF24",
    brightBlue: eyeCareTokens.primary,
    brightMagenta: "#9A3412",
    brightCyan: "#14B8A6",
    brightWhite: eyeCareTokens.textSecondary,
  },
};

export default terminalThemes;
